version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/src:/app
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    command: npm run dev
    volumes:
      - ./frontend/src:/app
    expose:
      - "3000"

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

